######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 25 21:52:38 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../../include/
QT -= gui

include(../../lib/FastCgiQt.pri)

# Input
HEADERS += HelloWorld.h
SOURCES += HelloWorld.cpp main.cpp
