######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 25 11:08:39 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT -= gui
QT += network

# Input
HEADERS += fastcgi.h Listener.h DebugHandler.h RecordHeader.h EnumHelpers.h
SOURCES += DebugHandler.cpp Listener.cpp RecordHeader.cpp main.cpp
